# Generated by Django 2.2 on 2021-10-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartlist_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlist',
            name='uid',
        ),
    ]
